#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
  /run/openvpn \
  /etc/openvpn/logs

# permissions
chown -R abc:abc \
  /etc/openvpn \
  /run/openvpn
chmod -R g+w \
  /etc/openvpn
chmod -R 644 \
  /etc/logrotate.d
